### ISSUE TITLE
[Bug]: Source map files for components point to invalid location when building a new themed Cloudscape library

### ISSUE THREAD

**Issue by jwwheeleriv** [cloudscape-design/theming-core#34]
### Package version

3.0.74

### node-versions

v16.13.2

### npm-versions

v8.1.2

### Description

When building a custom themed cloudscape package the source map files should point to valid locations.  The issue is the theming core builds the components based on @cloudscape-design/components-themeable which I assume imports the components library so the source code never exists on the user created project that is used to create the themed components .  The src location that the source map points (ie. ../../../src/[component name]/index.js) doesn't exist when the new themed components are created in the build output folder.  This creates warnings in frontend tooling systems like ViteJS when it cannot resolve the mapping and thus will create issues mapping the source to debuggers inside browsers.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/theming-core/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/theming-core/issues) for duplicate problems

**Comment by johannes-weber** [comment]
Hi @jwwheeleriv tanks for reporting, we'll take a look at the incorrect source mapping!

**Comment by johannes-weber** [comment]
Reproducing the warning you described was not successful on a fresh webpack and vite setup. Could you share your setup or steps on how to reproduce it?

Related to that:
We've made a change in the components package which set's the source map's `sourceRoot` path. This fixes the relative path the source maps point to. For details see https://github.com/cloudscape-design/components/pull/906.

_Nevertheless, we do not expose our source code in the NPM artifacts ([Link to the components package on UNPKG](https://www.unpkg.com/browse/@cloudscape-design/components@3.0.235/))_.

That's why we've added the `sourcesContent` field. The field holds the original source content and should be used when the files under `sources` can't be hosted ([link to specs](https://sourcemaps.info/spec.html)).
